tracks = [["Bounce Back", "Big Sean"],
["Love That Sound (Feat. Jeremih)", "Sayyi"],
["Welcome To LA", "Oliver Tree"],
["Lady Villain", "Daye Jack"],
["All Around The World (Feat. Desiigner)", "Mura Masa"],
["Caroline", "Amine"],
["Fake Love", "Drake"],
["Monster (Feat. Jay-Z, Rick Ross, Nicki Minaj & Bon Iver)", "Kanye West"],
["Hold On We`re Going Home (Feat. Majid Jordan)", "Drake"],
["I Don`t Fuck With You (Feat. E-40)", "Big Sean"],
["Tiimmy Turner (Feat. Kanye West) (Remix)", "Desiigner"],
["Father Stretch My Hands Pt. 1", "Kanye West"],
["In My Room (Feat. Ty Dolla $ign & Tyga)", "Yellow Claw"],
["Holiday (Feat. Snoop Dogg, John Legend & Takeoff)", "Calvin Harris"],
["Shooting Stars", "Bag Raiders"],
["Smoke Bomb (Feat. Snoop Dogg)", "Datsik"],
["Temple (Feat. M.I.A. & G-Dragon)", "Baauer"],
["I Like Tuh (Feat. I Love Makonnen)", "Carnage"],
["Spotless", "Martin Garrix"],
["Not Going Home (Feat. Gia Koka)", "DVBBS"],
["Nobody Speak (Feat. Run The Jewels)", "DJ Shadow"],
["Make Up Your Mind", "Martin Garrix"],
["Would I Lie To You (Radio Edit)", "David Guetta"],
["Wiee", "Martin Garrix"],
["Sun Is Never Going Down (Feat. Dawn Golden)", "Martin Garrix"],
["Too Original (Feat. Elliphant & Jovi Rockwell) (아이폰 - 사랑 CF 삽입곡)", "Major Lazer"],
["Dessert", "Dawin"],
["Wild For The Night (Feat. Skrillex And Birdy Nam Nam)", "A$AP Rocky"],
["Five More Hours (Single)", "Chris Brown"],
["Dessert (Remix)", "Dawin"],
["SXWME (Feat. 박재범) (Prod. By MNEK)", "Far East Movement"],
["I Know There`s Gonna Be (Good Times) (Feat. Young Thug & Popcaan) (아이폰6로찍다 CF 배경음악)", "Jamie XX"],
["Miss Primetime (Feat. Pell)", "Big Gigantic"],
["The Half (Feat. Swizz Beatz, Jeremih & Young Thug)", "DJ Snake"],
["Together", "Martin Garrix"],
["This Time", "Axwell"],
["This Is What You Came For (Feat. Rihanna)", "Calvin Harris"],
["Feels (Feat. Pharrell Williams, Katy Perry & Big Sean)", "Calvin Harris"],
["Doctor Pepper", "Diplo"],
["All Of Me (Feat. Logic, Rozes)", "Big Gigantic"],
["Heatstroke (Feat. Young Thug, Pharrell Williams & Ariana Grande)", "Calvin Harris"],
["Starboy (Feat. Daft Punk)", "The Weeknd"],
["Don`t Wanna Fall In Love", "Kyle"],
["False Alarm", "The Weeknd"],
["Hold On & Believe (Feat. The Federal Empire)", "Martin Garrix"],
["Deja Vu (Feat. Justin Bieber)", "Post Malone"],
["Cash Out (Feat. ScHoolboy Q, PARTYNEXTDOOR & D.R.A.M.)", "Calvin Harris"],
["Party Up (Feat. YG)", "Destructo"],
["Ongoing Thing (Feat. Oddisee)", "20syl"],
["Bad Things", "MGK"]]
